config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'shortened_urls#index'
  get "/stats", to: 'shortened_urls#stats'
  get "/:short_url", to: 'shortened_urls#show'
  get "shortened/:short_url", to: 'shortened_urls#shortened', as: :shortened
  post "/shortened_urls/create"
  get "/shortened_urls/fetch_original_url"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/shortened_url.rb
class ShortenedUrl < ApplicationRecord
  has_many :shortened_url_analytics, dependent: :destroy

  # UNIQUE ID IS THE URL NAME THAT WILL APPEAR LIKE: http://localhost:3000/s3f1n
  UNIQUE_ID_LENGTH = 5
  validates :original_url, uniqueness: true
  validates :original_url, presence: true, on: :create
  validates_format_of :original_url, with: /\A(?:(?:http|https):\/\/)?([-a-zA-Z0-9.]{2,256}\.[a-z]{2,4})\b(?:\/[-a-zA-Z0-9@,!:%_\+.~#?&\/\/=]*)?\z/
  before_create :generate_short_url
  before_create :sanitize
  before_create :set_expiry_date

  #GENERATE A UNIQUE URL FOR GIVEN WEB ADDRESS BEFORE SAVING INTO DATABASE
  def generate_short_url
    url = ([*('a'..'z'),*('0'..'9')]).sample(UNIQUE_ID_LENGTH).join
    old_url = ShortenedUrl.where(short_url: url).last
    if old_url.present?
      self.generate_short_url
    else
      self.short_url = url
    end
  end

  #CHECK IF ANY URL URL EXIST BEFORE SAVING INTO DATABASE
  def find_duplicate
    ShortenedUrl.find_by_sanitize_url(self.sanitize_url)
  end

  def new_url?
    find_duplicate.nil?
  end

  #SANITIZE THE USER GIVEN URL
  def sanitize
    self.original_url.strip!
    self.sanitize_url = self.original_url.downcase.gsub(/(https?:\/\/)|(www\.)/, "")
    self.sanitize_url = "http://#{self.sanitize_url}"
  end

  def set_expiry_date
    self.expiry_date = self.created_at.next_month
  end
end

app/models/shortened_url_analytic.rb
class ShortenedUrlAnalytic < ApplicationRecord
  belongs_to :shortened_url
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/shortened_urls_controller.rb
class ShortenedUrlsController < ApplicationController
  before_action :find_url, only: [:show]

  def index
    @url = ShortenedUrl.new
  end

  def show
    if (@url.created_at..@url.expiry_date).include?(DateTime.now)
     @url.increment!(:clicks_count)
     analytics = @url.shortened_url_analytics.new
     analytics.ip_address = request.ip || '61.12.43.186'
     analytics.country = request.location.country || 'India'
     analytics.save
     redirect_to @url.sanitize_url
    else
     render :file => 'public/404.html', :status => :not_found, :layout => false
    end
  end

  def create
    @url = ShortenedUrl.new
    @url.original_url = params[:shortened_url][:original_url]
    @url.sanitize
    respond_to do |format|
      if @url.save
        host = request.host_with_port
        @short_url = 'http://' + host + '/' + @url.short_url
        format.js
        format.json { render json: @url, status: :created, location: @url }
      else
        format.js { render action: "index" }
        format.json { render json: @url.errors, status: :unprocessable_entity }
      end
    end
  end

  def stats
    @urls = ShortenedUrl.all
  end

  private
  def find_url
    @url = ShortenedUrl.find_by_short_url(params[:short_url])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shortened_urls_helper.rb
module ShortenedUrlsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UrlShortner</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shortened_urls/create.js.erb
$( "#shorten-url" ).replaceWith( "<%= @short_url %>" );

app/views/shortened_urls/index.html.erb
<p id="notice"><%= notice %></p>
<h2>Welcome to urlshortner.com</h2>
<%= form_with scope: :shortened_url, url: shortened_urls_create_path, local: false do |form| %>
  <p>
    <%= form.label :original_url, 'Please enter your URL here'%><br>
    <%= form.text_field :original_url %>
    <%= form.submit 'SHORTEN'%>
  </p>
<% end %>

<p>Here's your short URL!</p>
<div id="shorten-url"></div>

app/views/shortened_urls/stats.html.erb
<h2>Analytics</h2>
<% @urls.each do |url| %>
  <b><%= url.original_url %></b><br>
  <%host = request.host_with_port%>
  <%= 'http://' + host + '/' + url.short_url %>
  <br/><br/>
  Total clicks: <%= url.clicks_count %><br/>
  Top countries: <%= url.shortened_url_analytics.map(&:country).join(', ') %>
  <hr>
<% end %>